Fix missing template arguments before '(' token
Error Messege is showed in the following
===================Error Messege==================
cppclient/api_json.cc:275:46:
error: missing template arguments before '(' token
         confirmedBundlesMap.emplace(std::pair(address, b));